os:
  - linux
  - osx
language: node_js
node_js:
  - 4.0
  - 4.1
  - 4.2
  - 5.0
  - 5.1
  - 5.2
  - 5.3
  - 5.4
  - node
  - iojs
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-generator-nodemodule' ]; then cd .. && eval "mv $currentfolder generator-generator-nodemodule" && cd generator-generator-nodemodule; fi
